### ISSUE TITLE
NUT UPSD container won't remain started - it says that the hid usb device can't be found.

### ISSUE THREAD

**Issue by nicxvan** [instantlinux/docker-tools#13]
**What I'm trying to do**
Get NUT UPSD running

**The problem I'm having**
The container won't stay running.

**Error messages/logs**
Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892,
Network UPS Tools - Generic HID driver 0.41 (3.8.0-3220-g866b921892),
USB communication driver 0.33,
No matching HID UPS found,
Driver failed to start (exit status=1),

**O/S environment**
 - Distro: ubuntu 18.04
 - Docker version: Docker version 18.06.0-ce-dev, build 3dfd20c
 - Orchestrator (k8s, swarm, none): none, docker-compose

**Additional context**
Add any other context about the question here
I do see a /dev/usb/hiddev0 on the host machine. I set up a devices stanza and restarted it as well.
```
  nutups:
    container_name: nut_ups
    image: instantlinux/nut-upsd:2.7.4-r6
    environment:
      SERIAL: XXXXXXXXXXXXXX
    network_mode: bridge
    ports:
      - 3493:3493
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true
    secrets:
      - nut-upsd-password
```
