### ISSUE TITLE
[SAMBA-DC] How can I upload data in ldif (or any other) format?

### ISSUE THREAD

**Issue by gredwhite** [instantlinux/docker-tools#134]
I use following docker-compose file:

```
version: '3.4'

services:
  samba:
    image: instantlinux/samba-dc:latest
    container_name: samba-dc
    cap_add:
      - CAP_SYS_ADMIN
    hostname: my.company
    environment:
      DOMAIN_ACTION: provision
      REALM: inno.tech
    volumes:
      - etc:/etc/samba
      - lib:/var/lib/samba
    ports:
      - "389:389"
    secrets:
      - samba-admin-password

volumes:
  etc:
  lib:

secrets:
  samba-admin-password:
    file: secrets.yaml
```
I have ldif file and I want to upload it to server ? Is there way to do it ? I tried to do it via **samba-tool** but no luck. please help
