### ISSUE TITLE
nut-upsd container eventually goes stale and doesn't restart - Tripp Lite UPS

### ISSUE THREAD

**Issue by nicxvan** [instantlinux/docker-tools#14]
```
4495.562591	Poll UPS [ups@localhost] failed - Data stale
4500.563466	Poll UPS [ups@localhost] failed - Data stale
4505.564242	Poll UPS [ups@localhost] failed - Data stale
4510.565056	Poll UPS [ups@localhost] failed - Data stale
```

Current docker compose setup

```
  nutups:
    container_name: nut_ups
    restart: always
#    build:
#      context: ./containers/nutupsd
    image: instantlinux/nut_upsd:latest
    environment:
      - vendorid=09ae
      - desc="Tripp Lite SMART1500LCD"
    network_mode: host
    ports:
      - 3493:3493
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true
    secrets:
      - nut-upsd-password
secrets:
  nut-upsd-password:
    file: ./nutpass
```

Restarting the container manually allows the values to be read again.

**Comment by nicxvan** [comment]
Got a pr set up that should add the Poll interval argument.

**Comment by instantlinux** [comment]
Accepted your PR and updated for alphabetical sort order.

**Comment by instantlinux** [comment]
Please re-open this issue if you find any instability.

**Comment by nlighteneddesign** [comment]
@instantlinux I can't reopen this, but it still happens. It seems to take longer to time out but eventually it does and the container doesn't restart itself. When I do restart the container I do get values output for a few hours.

The logs start out like this:
```
47366.262502	Poll UPS [ups@localhost] failed - Data stale
47371.262966	Poll UPS [ups@localhost] failed - Data stale
47376.263825	Poll UPS [ups@localhost] failed - Data stale
47381.264334	Poll UPS [ups@localhost] failed - Data stale
47386.265203	Poll UPS [ups@localhost] failed - Data stale
47391.265502	Poll UPS [ups@localhost] failed - Data stale
47396.266256	Poll UPS [ups@localhost] failed - Data stale
47401.267114	Poll UPS [ups@localhost] failed - Data stale
47406.267569	Poll UPS [ups@localhost] failed - Data stale
47406.267620	UPS ups@localhost is unavailable
sh: wall: not found
```

and eventually resolve to this:
```
70019.986794	UPS [ups@localhost]: connect failed: Connection failure: Operation timed out
70019.986855	UPS ups@localhost is unavailable
sh: wall: not found
70024.987605	Trying to connect to UPS [ups@localhost]
70155.154787	UPS [ups@localhost]: connect failed: Connection failure: Operation timed out
70160.155107	Trying to connect to UPS [ups@localhost]
```

Here is my docker-compose.yml
```
  nutups:
    container_name: nut_ups
    restart: always
#    build:
#      context: ./containers/nutupsd
    image: instantlinux/nut-upsd:latest
    environment:
      - VENDORID=09ae
      - DESCRIPTION=Tripp Lite SMART1500LCD
      - POLLINTERVAL=12
    network_mode: host
    ports:
      - 3493:3493
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true
    secrets:
      - nut-upsd-password
```
