### ISSUE TITLE
Can't start /usr/lib/nut/usbhid-upsd: No such file or directory

### ISSUE THREAD

**Issue by eboddington** [instantlinux/docker-tools#158]
I'm running in Docker Compose with this setup:
```
nut-upsd:
    image: instantlinux/nut-upsd
    environment:
      - TZ=Europe/London
      - DRIVER=usbhid-upsd
      - API_PASSWORD=foobar
      - MAXAGE=25
    devices:
      - /dev/bus/usb/002:/dev/bus/usb/002
    ports:
      - 3493:3493
    restart: always
    privileged: true
```

The UPS is a CyberPower CP900EPFCLCD connected via USB and `lsusb` shows it. But the container just goes into a restart loop with the logs showing these lines repeating:
```
nut-upsd-1  | Network UPS Tools - UPS driver controller 2.8.2
nut-upsd-1  | Can't start /usr/lib/nut/usbhid-upsd: No such file or directory
```
