### ISSUE TITLE
Tripp-Lite issues with nut-upsd image - still happening

### ISSUE THREAD

**Issue by instantlinux** [instantlinux/docker-tools#17]
Another user @nlighteneddesign reports this:

It seems to take longer to time out but eventually it does and the container doesn't restart itself. When I do restart the container I do get values output for a few hours.

The logs start out like this:
```
47366.262502	Poll UPS [ups@localhost] failed - Data stale
47371.262966	Poll UPS [ups@localhost] failed - Data stale
47376.263825	Poll UPS [ups@localhost] failed - Data stale
47381.264334	Poll UPS [ups@localhost] failed - Data stale
47386.265203	Poll UPS [ups@localhost] failed - Data stale
47391.265502	Poll UPS [ups@localhost] failed - Data stale
47396.266256	Poll UPS [ups@localhost] failed - Data stale
47401.267114	Poll UPS [ups@localhost] failed - Data stale
47406.267569	Poll UPS [ups@localhost] failed - Data stale
47406.267620	UPS ups@localhost is unavailable
sh: wall: not found
```

and eventually resolve to this:
```
70019.986794	UPS [ups@localhost]: connect failed: Connection failure: Operation timed out
70019.986855	UPS ups@localhost is unavailable
sh: wall: not found
70024.987605	Trying to connect to UPS [ups@localhost]
70155.154787	UPS [ups@localhost]: connect failed: Connection failure: Operation timed out
70160.155107	Trying to connect to UPS [ups@localhost]
```

Here is my docker-compose.yml
```
  nutups:
    container_name: nut_ups
    restart: always
#    build:
#      context: ./containers/nutupsd
    image: instantlinux/nut-upsd:latest
    environment:
      - VENDORID=09ae
      - DESCRIPTION=Tripp Lite SMART1500LCD
      - POLLINTERVAL=12
    network_mode: host
    ports:
      - 3493:3493
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true
    secrets:
      - nut-upsd-password
```
