### ISSUE TITLE
nut-upsd - Include usbutils in the image?

### ISSUE THREAD

**Issue by jkaberg** [instantlinux/docker-tools#183]
I have an stupid UPS that I can't get working correctly without resolving to softreset the USB port/UPS from time to time with `usbreset` from [usbutils](https://pkgs.alpinelinux.org/package/edge/main/x86/usbutils). I was wondering if you'd consider adding it to the image? 

My setup/workflow will then be:

1. `usbreset device && entrypoint.sh`
2. NUT running
3. Container exit/crash due to nut->Stale Data/connection lost
4. Container restarts

Its not an very elegant solution, but it works reliably. I did briefly research NUT to see if there was any built in events to trigger such tool/command however I did not find any

Oh and thanks for the container!

**Comment by jkaberg** [comment]
Nevermind, doesn't seem usbutils packages `usbreset` unlike the Ubuntu equilavent. So I did it like so;

docker-compose.yml
```
  nut:
    image: instantlinux/nut-upsd
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb
    entrypoint: ["/etc/nut/reset_ups.sh"]
    volumes:
      - /media/config/nut:/etc/nut
    networks:
      - hastnet
```


reset_ups.sh
```
#!/bin/sh

# Define the USB device ID
VENDOR_ID="06da"
PRODUCT_ID="ffff"

# Find the USB device path in sysfs
USB_PATH=""
for vendor_file in /sys/bus/usb/devices/*/idVendor; do
    if [ "$(cat "$vendor_file")" = "$VENDOR_ID" ]; then
        product_file="${vendor_file%/*}/idProduct"
        if [ -f "$product_file" ] && [ "$(cat "$product_file")" = "$PRODUCT_ID" ]; then
            USB_PATH="${vendor_file%/*}"
            break
        fi
    fi
done

if [ -z "$USB_PATH" ]; then
    echo "Error: Device not found"
    exit 1
fi

# Perform the USB port reset
echo "Resetting USB device at $USB_PATH"
echo "0" > "$USB_PATH/authorized"
sleep 1
echo "1" > "$USB_PATH/authorized"
echo "USB device reset complete"

/usr/local/bin/entrypoint.sh
```
