### ISSUE TITLE
Can't get Cyber Power UPS to work

### ISSUE THREAD

**Issue by Tardymo** [instantlinux/docker-tools#24]
I'm trying to monitor Cyber Power UPS connected to RPi 3B, but all I gen in logs when starting the container is:
```
Network UPS Tools - UPS driver controller 3.8.0-3727-geade014bef
Network UPS Tools - Generic HID driver 0.41 (3.8.0-3727-geade014bef)
USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
```
lsusb show my UPS is connected:
`Bus 001 Device 005: ID 0764:0601 Cyber Power System, Inc. PR1500LCDRT2U UPS`

I'm not sure I am doing it correctly, but I created a following udev rule in /etc/udev/rules.d/10-ups.rules
`ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="0764", ATTR{idProduct}=="0601", MODE="0666", SYMLINK+="ups0"`
and I made sure /dev/ups0 symlink has been created

Finally, here is what I currently have in docker-compose.yml
```
 nutups:
    container_name: nut_ups
    restart: unless-stopped
    image: instantlinux/nut-upsd-arm32
    environment:
      - VENDORID=0764
    ports:
      - 3493:3493
    secrets:
      - nut-upsd-password
    devices:
      - /dev/ups0:/dev/ups0
    privileged: true
```

Initially I had this configuration without passing VENDORID variable and /dev/ups0 device. Not sure what to do next. A year or two ago I got it working on the same RPi using the same UPS when installing nut directly without docker, so I know it should work.

**Comment by ugomeda** [comment]
Hi, if that's any help and not too late : i had to mount `/dev/bus/usb` into my container to have NUT detecting my device :

```
  networkupstools:
    image: instantlinux/nut-upsd
    privileged: true
    restart: always
    mem_limit: 128m
    cpus: 1
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./ups.conf:/etc/nut/local/ups.conf:ro
      - ./secrets/nut-upsd-password:/run/secrets/nut-upsd-password:ro
```
