### ISSUE TITLE
samba-dc: multiple WERR_DNS_ERROR_RECORD_ALREADY_EXISTS

### ISSUE THREAD

**Issue by ichundu** [instantlinux/docker-tools#39]
Hello,

I'm getting the following error multiple times when running `docker-compose up -d`.
This was referenced in this [issue](https://github.com/instantlinux/docker-tools/issues/27) also

```
/usr/sbin/samba_dnsupdate: ERROR(runtime): uncaught exception - (9711, 'WERR_DNS_ERROR_RECORD_ALREADY_EXISTS')
/usr/sbin/samba_dnsupdate:   File "/usr/lib/python3.8/site-packages/samba/netcmd/__init__.py", line 186, in _run
/usr/sbin/samba_dnsupdate:     return self.run(*args, **kwargs)
/usr/sbin/samba_dnsupdate:   File "/usr/lib/python3.8/site-packages/samba/netcmd/dns.py", line 945, in run
/usr/sbin/samba_dnsupdate:     raise e
/usr/sbin/samba_dnsupdate:   File "/usr/lib/python3.8/site-packages/samba/netcmd/dns.py", line 940, in run
/usr/sbin/samba_dnsupdate:     dns_conn.DnssrvUpdateRecord2(dnsserver.DNS_CLIENT_VERSION_LONGHORN,
```

Here is my docker-compose.yml:
```yaml
version: "3.1"

services:
  app:
    container_name: samba_dc
    image: ${REGISTRY_URI:-instantlinux}/samba-dc:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_ADMIN
    hostname: ${SAMBADC_HOSTNAME:-dc.example.com}
    environment:
      DOMAIN_ACTION: ${SAMBADC_DOMAIN_ACTION:-join}
      INTERFACES: ${SAMBADC_INTERFACES:-lo eth0}
      REALM: ${SAMBA_REALM:-ad.example.com}
      TZ: ${TZ:-UTC}
      WORKGROUP: ${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
      - etc:/etc/samba
      - lib:/var/lib/samba
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
      - 49152-65535
    secrets:
      - samba-admin-password

volumes:
  etc:
  lib:
secrets:
  samba-admin-password:
    file: /etc/samba/samba-admin-password
```
