### ISSUE TITLE
"Interrupted system call" on starting nut-upsd

### ISSUE THREAD

**Issue by Cyber1000** [instantlinux/docker-tools#7]
Hi,

Thanks for the image nut-upsd, I wanted to add some changes and tried to build the image before making my changes. It worked, but when starting with docker-compose I'm getting the following (first line seems to be the problem):

> /usr/local/bin/entrypoint.sh: line 26: can't create /etc/nut/ups.conf: Interrupted system call
> Network UPS Tools - UPS driver controller 3.7.0-4118-g91b32f90c7
> Error: no UPS definitions found in ups.conf
> fopen /var/run/nut/upsd.pid: No such file or directory
> Network UPS Tools upsd 3.7.0-4118-g91b32f90c7
> listening on 0.0.0.0 port 3493
> Warning: no UPS definitions in ups.conf
> Fatal error: at least one UPS must be defined in ups.conf
> Network UPS Tools upsmon 3.7.0-4118-g91b32f90c7

When I look into the container a /etc/nut/ups.conf exists, but only the commented-out-part not the lines which should have been added.
The 2 other files get appended.

Any ideas?
Thanks!

**Comment by Cyber1000** [comment]
After some testing it seems that it has nothing to do with my fork, I retested with this repository and the same docker-compose which is in this repository and getting the same issue.

But a restart mostly helps, so it seems to come occasionally, I have found a similar problem (https://github.com/Landoop/kafka-topics-ui/issues/77) which had the problem on the EOF line too, it seems like a kind of racecondition to me.

Sometimes it's only ups.conf, sometimes all conf-files in the entrypoint.sh, sometimes it works, but within five restarts I have at least one failure. 
I'm using:
- host: ubuntu 18.04 LTS
- docker: 18.06.1-ce
- docker-compose: 1.22.0

I assume this doesn't happen to you?

**Comment by Cyber1000** [comment]
Had the same problem on a second computer (thought at first that it was the empty serial-number, cause my second computer has another UPS), but it was exactly the same with an older ubuntu host. Fxied it with some sort of template on my own image now (the entrypoint is quite different from this, so no easy merging possible)

If you see similar issues on your computer(s), feel free to ask. If nobody seeing the same issue, when executing "docker logs {yourdockerservice}" we may close this task.

**Comment by Cyber1000** [comment]
Hi,
Did you have time to try?
As said I'm using my own image without EOF magic, but just to know if we should close this issue.

Greetings!

**Comment by instantlinux** [comment]
Sorry for the delay looking at this: yes, I can reproduce similar symptoms by restarting a few times.

**Comment by instantlinux** [comment]
I've pushed an update to the image 2.7.4-r6 at [instantlinux/nut-upsd|https://hub.docker.com/r/instantlinux/nut-upsd]. Try it and see if it fully addresses your symptoms.

**Comment by nicxvan** [comment]
I was still getting this on latest. I switched to 2.7.4-r6 and the error went away. I still don't have it up and running cause it says there is no HID UPS but I will research that error.

**Comment by nicxvan** [comment]
I might have spoken too soon, restarting a couple of times I still see it occasionally.

**Comment by nicxvan** [comment]
It fails and just says it's stale, it is set to restart: unless-stopped, but the container doesn't die when it gets stale.

I will try latest and report back.

**Comment by nicxvan** [comment]
Ok it's connected using latest: here is the docker-compose. I will keep an eye on it and let you know if it becomes stale and auto restarts.

I think I had to remove the serial number that seemed to help too.

```
  nutups:
    container_name: nut_ups
    restart: unless-stopped
#    build:
#      context: ./containers/nutupsd
    image: instantlinux/nut_upsd:latest
    environment:
      - vendorid=09ae
      - desc="Tripp Lite SMART1500LCD"
    network_mode: host
    ports:
      - 3493:3493
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true
    secrets:
      - nut-upsd-password
secrets:
  nut-upsd-password:
    file: ./nutpass
```
