### ISSUE TITLE
Reporting 0% load

### ISSUE THREAD

**Issue by Daniel-dev22** [instantlinux/docker-tools#92]
I'm using the nut integration in home assistant which is a nut client. I'm getting a load of 0% which isn't true. I even set the scan interval to the same as the poll interval of 15 and got nothing. Set it to 10 seconds got nothing. When nut starts sometimes I get 3%. Randomly I can see at night I got as high as 5%. But never consistently reporting.
![Screenshot_20221108_054455](https://user-images.githubusercontent.com/47092714/200544593-677f037e-191a-4f1e-97f7-15ae77f2e586.jpg)

Docker Compose
```
services:
  nut-upsd:
    privileged: true
    container_name: nut-upsd
    image: instantlinux/nut-upsd:latest
    restart: unless-stopped
    environment:
      #POLLINTERVAL: 15
      #POLLFREQ: 15
      SERIAL: CXXLY7002253
      API_PASSWORD: "redacted"
      #VENDORID: 0x0764
      DRIVER: usbhid-ups
    ports:
      - 3493:3493
```
No errors in logs. Here's what the logs show. I assume I should see more here if it was reading it?

Network UPS Tools - UPS driver controller 20220715-1528-g06e97bf49f
Network UPS Tools - Generic HID driver 0.47 (20220715-1528-g06e97bf49f)
Using subdriver: CyberPower HID 0.6
USB communication driver (libusb 1.0) 0.43
Ignoring invalid pid number 0
Network UPS Tools upsd 20220715-1528-g06e97bf49f
listening on 0.0.0.0 port 3493
Connected to UPS [ups]: usbhid-ups-ups
   0.000000	Ignoring invalid pid number 0
Network UPS Tools upsmon 20220715-1528-g06e97bf49f
   0.000089	Using power down flag file /etc/killpower
   0.000142	UPS: ups@localhost (primary) (power value 1)
   0.000153	[D1] debug level is '1'
   0.000169	[D1] debug level is '1'
   0.000270	[D1] Saving PID 24 into /var/run/upsmon.pid
Init SSL without certificate database
   0.000956	[D1] Trying to connect to UPS [ups@localhost]
   0.001118	[D1] Logged into UPS ups@localhost
